---
title: "linear_models"
author: "Chuyue Xiang"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

Fit a first linear model!

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit

summary(fit)
```

tidy the resukts instead!

```{r}
fit %>% 
  broom::tidy()
  mutate(term = str_replace(term, "boro", "Boro:")) %>% 
  knitr::kable(digits = 3)
  
  fit %>% 
    broom::glance()
```

## Take a look at factors ... 

```{r}
nyc_airbnb = 
nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),
    room_type = fct_infreq(room_type)
  )
```

refit the linear model

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)
fit
```

```{r}
fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^boro", "Boro: ")) %>% 
  knitr::kable(digits = 3)
```

## disgnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) +
  geom_point()+
         ylim(-500,500)
```

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + geom_point()

modelr::add_predictions(nyc_airbnb, fit)
```

## Nesting

```{r}
fit_interaction = lm(price~stars* boro + room_type * boro, data = nyc_airbnb)

fit_interaction %>%
  broom::tidy()
  
```

```{r}
nyc_airbnb %>% 
  filter(boro == "Brooklyn") %>%
  lm(price~stars + room_type, data = .) %>% 
  broom::tidy()
```

Let's try to map this instead

```{r}
nyc_airbnb %>% 
  nest(data = - boro) %>% 
  mutate(
    models = map(.x = data, ~lm(price~stars+ room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
    unnest(results)
  
```

